global:
  scrape_interval:     10s
  evaluation_interval: 5s

scrape_configs:
# The job name assigned to scraped metrics by default.
- job_name: statsd
  consul_sd_configs:
  - server: localhost:8500
    services:
    - "statsd"

- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
